<?php

use Drupal\node\Entity\NodeType;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\field\Entity\FieldConfig;
use Drupal\Core\Entity\Entity\EntityFormDisplay;
use Drupal\Core\Entity\Entity\EntityViewDisplay;

/**
 * Implements hook_install().
 */
function tv_schedule_install() {
  // Создаем тип контента Program.
  $node_type = NodeType::create([
    'type' => 'program',
    'name' => 'Program',
  ]);
  $node_type->save();

  // Добавляем поля к типу контента Program.
  $fields = [
    'field_program_time' => ['label' => 'Time', 'field_type' => 'datetime', 'widget_type' => 'datetime_default', 'display_type' => 'datetime_default'],
    'field_program_description' => ['label' => 'Description', 'field_type' => 'string', 'widget_type' => 'string_textfield', 'display_type' => 'string'],
  ];

  foreach ($fields as $field_name => $field_info) {
    $field_storage = FieldStorageConfig::create([
      'field_name' => $field_name,
      'entity_type' => 'node',
      'type' => $field_info['field_type'],
    ]);
    $field_storage->save();

    $field_instance = FieldConfig::create([
      'field_storage' => $field_storage,
      'bundle' => 'program',
      'label' => $field_info['label'],
    ]);
    $field_instance->save();

    // Устанавливаем виджет формы по умолчанию.
    $form_display = EntityFormDisplay::load('node.program.default');
    if (!$form_display) {
      $form_display = EntityFormDisplay::create([
        'targetEntityType' => 'node',
        'bundle' => 'program',
        'mode' => 'default',
        'status' => TRUE,
      ]);
    }
    $form_display->setComponent($field_name, [
      'type' => $field_info['widget_type'],
    ])->save();

    // Устанавливаем отображение поля по умолчанию.
    $view_display = EntityViewDisplay::load('node.program.default');
    if (!$view_display) {
      $view_display = EntityViewDisplay::create([
        'targetEntityType' => 'node',
        'bundle' => 'program',
        'mode' => 'default',
        'status' => TRUE,
      ]);
    }
    $view_display->setComponent($field_name, [
      'type' => $field_info['display_type'],
    ])->save();
  }
}

/**
 * Implements hook_uninstall().
 */
function tv_schedule_uninstall() {
  // Удаление созданного типа контента и его полей.
  $node_type = NodeType::load('program');
  if ($node_type) {
    $node_type->delete();
  }

  $fields = [
    'field_program_time',
    'field_program_description',
  ];

  foreach ($fields as $field_name) {
    if ($field_storage = FieldStorageConfig::loadByName('node', $field_name)) {
      $field_storage->delete();
    }
  }
}
